replicaCount: 1
image:
  repository: vitaliidenysiuk97/simple-app-final
  tag: v0.0.1
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 80
ingress:
  tls:
    enabled: false
    secretName: simple-app-tls
  enabled: true
  className: nginx
  host: app.local
  path: /
resources: {}
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
env:
  DATABASE_URL: ""
  APP_STORE: ""
  APP_REDIS_URL: ""