replicaCount: 2

image:
  repository: vitaliidenysiuk97/simple-app-final
  tag: v0.0.1
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: nginx
  host: app.local
  path: /

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

env:
  DATABASE_URL: "postgresql://app:app@postgres-rw:5432/app"
  REDIS_URL: "redis://dragonfly:6379"