apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: simple-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
           - name: DATABASE_URL
              value: {{ .Values.env.DATABASE_URL | quote }}
            - name: APP_STORE
              value: {{ .Values.env.APP_STORE | quote }}
            - name: APP_REDIS_URL
              value: {{ .Values.env.APP_REDIS_URL | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
